//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace carousel_v1_mvc.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Game
    {
        public System.Guid GameID { get; set; }
        public string GameThumbnail { get; set; }
        public string GamePreview { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    }
}
